var img;
var arrowLeft;
var arrowRight;
var arrowUp;
var arrowDown;
var arrowToward;
var arrowAway;
var aslThree;
var aslFive;

function setup() {
  createCanvas(window.innerWidth,window.innerHeight);
  img = loadImage('https://i.imgur.com/4Tk1yjY.jpg');
  arrowLeft = loadImage('https://i.imgur.com/oE5RKNL.jpg');
  arrowRight = loadImage('https://i.imgur.com/AziaAoM.jpg');
  arrowUp = loadImage('https://i.imgur.com/ctU06lg.jpg');
  arrowDown = loadImage('https://i.imgur.com/5QJps1f.jpg');
  arrowToward = loadImage('https://i.imgur.com/bOtXWSW.jpg');
  arrowAway = loadImage('https://i.imgur.com/0WBp1OF.jpg');
  aslZero = loadImage('https://i.imgur.com/rsj36ea.jpg');
  aslOne = loadImage('https://i.imgur.com/arMWyzi.jpg');
  aslTwo = loadImage('https://i.imgur.com/BgFbQbC.jpg');
  aslThree = loadImage('https://i.imgur.com/EEpPbsZ.jpg');
  aslFour = loadImage('https://i.imgur.com/4Hhk8uj.jpg');
  aslFive = loadImage('https://i.imgur.com/P1eedg9.jpg');
  aslSix = loadImage('https://i.imgur.com/UhuaSOt.jpg');
  aslSeven = loadImage('https://i.imgur.com/IMEizJ4.jpg');
  aslEight = loadImage('https://i.imgur.com/gFTfbRZ.jpg');
  aslNine = loadImage('https://i.imgur.com/dObfcoO.jpg');
  aslZeroDigit = loadImage('https://i.imgur.com/3Uo7rVL.jpg');
  aslOneDigit = loadImage('https://i.imgur.com/0UbYtfk.jpg');
  aslTwoDigit = loadImage('https://i.imgur.com/BDqc8LL.jpg');
  aslThreeDigit = loadImage('https://i.imgur.com/p2wSuN6.jpg');
  aslFourDigit = loadImage('https://i.imgur.com/Kvt5Zm8.jpg');
  aslFiveDigit = loadImage('https://i.imgur.com/CL0KpjA.jpg');
  aslSixDigit = loadImage('https://i.imgur.com/vKQHrzo.jpg');
  aslSevenDigit = loadImage('https://i.imgur.com/V1sPABb.jpg');
  aslEightDigit = loadImage('https://i.imgur.com/OLdbXjr.jpg');
  aslNineDigit = loadImage('https://i.imgur.com/yuI5xXC.jpg');
  question1 = loadImage('https://i.imgur.com/SQwPuLv.jpg');
  question2 = loadImage('https://i.imgur.com/9ycB9bm.jpg');
  question3 = loadImage('https://i.imgur.com/W9IoGU3.jpg');
  question4 = loadImage('https://i.imgur.com/YwjezN6.jpg');
  question5 = loadImage('https://i.imgur.com/DRZ4mxW.jpg');
  question6 = loadImage('https://i.imgur.com/4quYMBT.jpgs');
  question7 = loadImage('https://i.imgur.com/izuTKFY.jpg');
  question8 = loadImage('https://i.imgur.com/4w6FGyr.jpg');
}
